# This is a basic workflow to build and upload Webchat to S3 bucket with Github Actions

name: Revenge Porn(UK) Staging release

# Controls when the action will run.
on:
  workflow_dispatch
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # Create and fill secret.ts
      - name: Create secret.ts
        run: |
          touch ./private/secret.ts
      - name: Fill secret.ts
        run: |
          cat <<EOT >> ./private/secret.ts
          export const API_KEY = '${{ secrets.IP_FIND_API_KEY }}';
          export const SERVERLESS_URL = '${{ secrets.STG_UK_SERVERLESS_URL }}';
          EOT
      # Run a single command using the runners shell to install dependencies 
      - name: Install dependencies
        run: npm install
      # Build and compile Webchat
      - name: Run build command
        run: npm run build:uk-staging
      # Rename the builded js file
      - name: Rename js
        run: mv bundle.js aselo-chat.min.js
        working-directory: ./build
      # Upload Webchat to S3 bucket
      - name: Upload Webchat to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --exclude '*' --include '*.js' --content-type 'application/javascript; charset=utf-8'
        env:
          AWS_S3_BUCKET: tl-public-chat-uk-stg
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          SOURCE_DIR: 'build'

      # Get AWS parameters
      - name: Set GITHUB_ACTIONS_SLACK_BOT_TOKEN
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "GITHUB_ACTIONS_SLACK_BOT_TOKEN"
          env_variable_name: "GITHUB_ACTIONS_SLACK_BOT_TOKEN"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
      - name: Set ASELO_DEPLOYS_CHANNEL_ID
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "ASELO_DEPLOYS_CHANNEL_ID"
          env_variable_name: "ASELO_DEPLOYS_CHANNEL_ID"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
      # Send Slack notifying success
      - name: Slack Aselo channel
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          channel-id: ${{ env.ASELO_DEPLOYS_CHANNEL_ID }}
          slack-message: "`[WEBCHAT]` Action ${{ github.workflow }} completed with SHA ${{ github.sha }} :rocket:."
        env:
          SLACK_BOT_TOKEN: ${{ env.GITHUB_ACTIONS_SLACK_BOT_TOKEN }}